added label check on pr action

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -10,6 +10,15 @@ env:
   PNPM_VERSION: 8
 
 jobs:
+  check:
+    runs-on: ubuntu-latest
+    if: "!(contains(github.event.pull_request.labels.*.name, 'frontend') || contains(github.event.pull_request.labels.*.name, 'backend') || contains(github.event.pull_request.labels.*.name, 'devops') || contains(github.event.pull_request.labels.*.name, 'infrastructure'))"
+    steps:
+      - name: message
+        run: |
+          echo "Required label '(frontend, backend, devops, infrastructure)' not found."
+          exit 1
+
   build:
     runs-on: ubuntu-latest
     steps:
